### ISSUE TITLE
About constrained edge?

### ISSUE THREAD

**Issue by yumianhuli2** [spiroyster/delaunay#1]
Hello！
tess.addConstraint(delaunay::edge{0, 1});
0 means vertex 0
1 means vertex 1
That's the right way to think about it？

And  For example how do you add delaunay constraints on the picture below?Because I don't want to get a triangle for 457 and 647! 
![delaunay](https://user-images.githubusercontent.com/39210837/76175406-6bac1200-61e7-11ea-92d0-ae712a4119a4.jpg)

Thank U！

**Comment by yumianhuli2** [comment]
I added a boundary constrain on this polygon
code is：
        std::vector<delaunay::vector2> vertices({
                                                        delaunay::vector2(0, 0),
                                                        delaunay::vector2(1.0, 0),
                                                        delaunay::vector2(1.0, 1.0),
                                                        delaunay::vector2(0, 1.0),
                                                        delaunay::vector2(0.25, 0.5),
                                                        delaunay::vector2(0.75, 0.5),
                                                        delaunay::vector2(0.25, 1),
                                                        delaunay::vector2(0.75, 1),

                                                });


        delaunay::tessellator tess(vertices);


        tess.addConstraint(delaunay::edge{0, 1});
    tess.addConstraint(delaunay::edge{2, 1});
    tess.addConstraint(delaunay::edge{7, 2});
    tess.addConstraint(delaunay::edge{5, 7});
    tess.addConstraint(delaunay::edge{4, 5});
    tess.addConstraint(delaunay::edge{6, 4});
    tess.addConstraint(delaunay::edge{3, 6});
    tess.addConstraint(delaunay::edge{0, 3});

        std::list<delaunay::triangle> result = tess.getTriangles();


but I still got 457 and 647！ why？

**Comment by spiroyster** [comment]
Sorry for late reply. I will investgate this for you.

**Comment by spiroyster** [comment]
Hello, this is the wrong type of tessellator to achieve what you want. A delaunay tessellation will produce the convex hull of all the points (i.e a segment 6-7 will exist in the final tessellation). You need to use earclipping routine. Alternatively you can use contrained delaunay (contraints will be 6-4, 4-5 & 7-5... but you need to remove the triangles. This can be done by getting the centroid of each triangle and deducing if it is within the polygon (Point in polygon test). It would be easier to use earclipping method. I can recommend (https://github.com/mapbox/earcut.hpp) which has served me well.

Contraints simply force where a segment will be (within a polygon), but don't force the boundaries of the polygon (boundaries will always be convex hull with delaunay).

Hope this helps.
